# JVM args for Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED

# Force Gradle to use JDK 17 (important for AGP + Kotlin compatibility)
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home

# Make sure Kotlin and Java targets match
kotlin.jvm.target=17

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true
